[package]
name = "frd-video-ffmpeg"
version = "0.1.0"
edition = "2021"

[dependencies]
frd-core = { path = "../frd-core" }
frd-media-api = { path = "../frd-media-api" }
libloading = "=0.8.9"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Storage_FileSystem",
] }
